name: Upload File to Esper

on: [push]

jobs:
  upload-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload file to Esper
      uses: mheap/github-action-http-request@v1
      with:
        url: 'https://{{tenant_name}}-api.esper.cloud/api/v0/enterprise/{{enterprise_id}}/content/upload/'
        method: 'POST'
        headers: '{"Authorization": "Bearer ${{ secrets.ESPER_API_TOKEN }}"}'
        form: '{"key": "@samplefile.txt"}'
